In [1]:
import numpy as np

In [2]:
A = np.array([1, 2, 3])
A

array([1, 2, 3])

In [3]:
A. ndim

1

In [4]:
A.shape

(3,)

In [5]:
A.size

3

In [6]:
B = np.zeros((3, 2))
B

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
C = np.ones((3, 4))
C.shape

(3, 4)

In [8]:
D = np.full((2, 2), 7)
D

array([[7, 7],
       [7, 7]])

In [9]:
np.random.seed(0)
np.random.randn(3, 4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [10]:
np.linspace(0, 10, 21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [11]:
np.arange(0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

## Manipulation

In [12]:
A = np.zeros((3, 2))
B = np.ones((3, 2))
print(A)
print(B)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
C = np.concatenate((A, B), axis=0)
C

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
D = np.concatenate((A, B), axis=1)
D

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [15]:
C = C.reshape((3, 4))
C

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
D.ravel()

In [16]:
A = np.array([1, 2, 3])
A.shape

(3,)

In [17]:
A = A.reshape((A.shape[0], 1))
A.shape

(3, 1)

In [18]:
A = A.squeeze()
A.shape

(3,)

In [32]:
# Exercise

def initialize(m, n):
    M = np.random.randn(m, n)
    N = np.ones((m,1))
    return np.concatenate((M, N), axis=1)

In [33]:
initialize(3, 2)

array([[-1.61389785, -0.21274028,  1.        ],
       [-0.89546656,  0.3869025 ,  1.        ],
       [-0.51080514, -1.18063218,  1.        ]])