# Numpy Broadcasting

In [21]:
import numpy as np

In [22]:
np.random.seed(0)
A = np.random.randint(0, 10, (2, 3))
A

array([[5, 0, 3],
       [3, 7, 9]])

In [23]:
B = np.ones((2, 2))
B

array([[1., 1.],
       [1., 1.]])

In [24]:
A + B

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

Operands dimensions must be respectively equal or equal to 1

In [ ]:
A + 2

array([[ 7,  2,  5],
       [ 5,  9, 11]])

In [ ]:
C = np.ones((2, 1))
A + C

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])

In [ ]:
D = np.ones((1, 3))
A + D

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])

This also works

In [25]:
A = np.random.randint(0, 10, (1, 3))
B = np.random.randint(0, 10, (4, 1))
print(A)
print(B)

[[3 5 2]]
[[4]
 [7]
 [6]
 [8]]


In [26]:
A + B

array([[ 7,  9,  6],
       [10, 12,  9],
       [ 9, 11,  8],
       [11, 13, 10]])